select 
	NAME_TYPE_ACCOUNT,
	ACCOUNT_OWNER,
	NVL(PLF_ADDRESS, BANK_NAME) PLF_ADDRESS,
	NUMBER_ACCOUNT,
	COMPANY_NAME,
	DATE_BEGIN_RELATION,
	DATE_END_RELATION
from
	{1}.VIEW_ACCOUNT_RELATION
	left join {1}.TYPE_ACCOUNT using (TYPE_ACCOUNT_ID)
where retention_id=:p_retention_id