select CONTRACT_NUMBER, CONTRACT_DATE, 
    E.PER_NUM, E.EMP_LAST_NAME, E.EMP_FIRST_NAME, E.EMP_MIDDLE_NAME,
    (SELECT S.CODE_SUBDIV FROM {1}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    {1}.PADEG.CASE_SHORT_FIO(E.PER_NUM, 'родительный') STATEMENT_OF
from {0}.LOAN L
join {1}.TRANSFER T on L.TRANSFER_ID = T.TRANSFER_ID
join {1}.EMP E on T.PER_NUM = E.PER_NUM
where L.LOAN_ID = :p_LOAN_ID