select G.GUARANTOR_LOAN_ID, G.LOAN_ID, G.GUARANTOR_CONTRACT_NUMBER, 
    GUARANTOR_CONTRACT_DATE, G.TRANSFER_ID, T.PER_NUM,
    (SELECT E.EMP_LAST_NAME FROM {1}.EMP E WHERE E.PER_NUM = T.PER_NUM) EMP_LAST_NAME, 
    (SELECT E.EMP_FIRST_NAME FROM {1}.EMP E WHERE E.PER_NUM = T.PER_NUM) EMP_FIRST_NAME, 
    (SELECT E.EMP_MIDDLE_NAME FROM {1}.EMP E WHERE E.PER_NUM = T.PER_NUM) EMP_MIDDLE_NAME, 
    (SELECT S.CODE_SUBDIV FROM {1}.SUBDIV S WHERE S.SUBDIV_ID = T.SUBDIV_ID) CODE_SUBDIV,
    (SELECT MAX(CODE_SUBDIV) KEEP(DENSE_RANK LAST ORDER BY DATE_TRANSFER) FROM {1}.TRANSFER T1
    JOIN {1}.SUBDIV S1 on T1.SUBDIV_ID = S1.SUBDIV_ID 
    WHERE T1.WORKER_ID = T.WORKER_ID) REAL_CODE_SUBDIV,
    CASE WHEN (SELECT MAX(TYPE_TRANSFER_ID) KEEP(DENSE_RANK LAST ORDER BY DATE_TRANSFER) FROM {1}.TRANSFER T1
            JOIN {1}.SUBDIV S1 on T1.SUBDIV_ID = S1.SUBDIV_ID 
            WHERE T1.WORKER_ID = T.WORKER_ID) = 3 THEN 'X' 
    END SIGN_DISMISS  
from {0}.GUARANTOR_LOAN G
join {1}.TRANSFER T on G.TRANSFER_ID = T.TRANSFER_ID
where G.LOAN_ID = :p_LOAN_ID