select REFINANCING_RATE_ID, REFINANCING_RATE_DATE, 
    LEAD(REFINANCING_RATE_DATE-1,1,DATE '3000-01-01') OVER(ORDER BY REFINANCING_RATE_DATE) REFINANCING_RATE_DATE_END,
    REFINANCING_RATE
from {0}.REFINANCING_RATE
order by REFINANCING_RATE_DATE DESC