select ITEM_FIN_PLAN_ID, ITEM_DATE, 
	LEAD(ITEM_DATE-86399/86400,1,DATE '3000-01-01') OVER(PARTITION BY LOAN_COST_ITEM_ID ORDER BY ITEM_DATE) ITEM_DATE_END,
	ITEM_NOTE, ITEM_CODE, LOAN_COST_ITEM_ID,
    LOAN_COST_ITEM_NAME, LOAN_COST_ITEM_CODE
from {0}.ITEM_FIN_PLAN I
join {0}.LOAN_COST_ITEM using (LOAN_COST_ITEM_ID)