select CLIENT_ACCOUNT_ID, NUMBER_ACCOUNT, NUMBER_CARD, BANK_NAME, BANK_OFFICE
from {0}.CLIENT_ACCOUNT CA
join {0}.TYPE_BANK TB on CA.TYPE_BANK_ID = TB.TYPE_BANK_ID
join {1}.TRANSFER T on CA.TRANSFER_ID = T.TRANSFER_ID
where CA.TYPE_ACCOUNT_ID = 1 and T.PER_NUM = :p_PER_NUM